### ISSUE TITLE
Issue when running HARC in different datasets

### ISSUE THREAD

**Issue by juandaqugo** [shubhamchandak94/readcompression#9]
Hello developers, 
We installed HARC succesfully in Centos 7, but when running it to compress it throwedan error. We tested it over different datasets of our own (small, and medium size) and we got the problem writen below. Then we downloaded one of the files suggested by authors in the supplementary data and got the same exact error. In all of of the tests we tried both options: preserving and not preserving original reads.

Any help about what we should do ?
Thank you very much

*** Preprocessing ***
				SRR554369_1.fastq
				Read length: 100
				Total number of reads: 1657871
				Total number of reads without N: 1633521
				Preprocessing Done!
				src/reorder.cpp: In function ‘void reorder(std::bitset<200>*, bbhashdict*)’:
				src/reorder.cpp:685:42: error: ‘accumulate’ is not a member of ‘std’
				  std::cout << "Reordering done, "<< 
                                std::accumulate(unmatched,unmatched+num_thr,0) <<" were unmatched\n";

**Comment by shubhamchandak94** [comment]
Hi,
It was probably because of compiler version, some compilers need numeric library for std::accumulate function. I have now added the library to reorder.cpp. Can you try it again now?
By the way, you can also check out SPRING (https://github.com/shubhamchandak94/Spring/) which is a complete FASTQ compressor based on HARC. 
Regards,
Shubham

**Comment by juandaqugo** [comment]
I will try it very soon. Thank you very much.
